r2:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  r_arm_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - r2/right_arm/joint0
      - r2/right_arm/joint1
      - r2/right_arm/joint2
      - r2/right_arm/joint3
      - r2/right_arm/joint4
      - r2/right_arm/wrist/pitch
      - r2/right_arm/wrist/yaw
    gains:
      r2/right_arm/joint0: {p: 1000.0, d: 60, i: 100, i_clamp: 500.0}
      r2/right_arm/joint1: {p: 1000.0, d: 60, i: 100, i_clamp: 500.0}
      r2/right_arm/joint2: {p: 1000.0, d: 60, i: 100, i_clamp: 500.0}
      r2/right_arm/joint3: {p: 1000.0, d: 60, i: 100, i_clamp: 500.0}
      r2/right_arm/joint4: {p: 1000.0, d: 60, i: 100, i_clamp: 500.0}
      r2/right_arm/wrist/pitch: {p: 1000.0, d: 60, i: 100, i_clamp: 500.0}
      r2/right_arm/wrist/yaw: {p: 1000.0, d: 60, i: 100, i_clamp: 500.0}
    follow_joint_trajectory:
      joints:
        - r2/right_arm/joint0
        - r2/right_arm/joint1
        - r2/right_arm/joint2
        - r2/right_arm/joint3
        - r2/right_arm/joint4
        - r2/right_arm/wrist/pitch
        - r2/right_arm/wrist/yaw
      constraints:
        goal_time: 10.0
        r2/right_arm/joint0:
          goal: 0.2
        r2/right_arm/joint1:
          goal: 0.2
        r2/right_arm/joint2:
          goal: 0.2
        r2/right_arm/joint3:
          goal: 0.2
        r2/right_arm/joint4:
          goal: 0.2
        r2/right_arm/wrist/pitch:
          goal: 0.2
        r2/right_arm/wrist/yaw:
          goal: 0.2
      state_publish_rate:  25            # Override default
      action_monitor_rate: 30            # Override default
      stop_trajectory_duration: 0        # Override default


  l_arm_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - r2/left_arm/joint0
      - r2/left_arm/joint1
      - r2/left_arm/joint2
      - r2/left_arm/joint3
      - r2/left_arm/joint4
      - r2/left_arm/wrist/pitch
      - r2/left_arm/wrist/yaw
    gains:
      r2/left_arm/joint0: {p: 1000.0, d: 60, i: 100, i_clamp: 500.0}
      r2/left_arm/joint1: {p: 1000.0, d: 60, i: 100, i_clamp: 500.0}
      r2/left_arm/joint2: {p: 1000.0, d: 60, i: 100, i_clamp: 500.0}
      r2/left_arm/joint3: {p: 1000.0, d: 60, i: 100, i_clamp: 500.0}
      r2/left_arm/joint4: {p: 1000.0, d: 60, i: 100, i_clamp: 500.0}
      r2/left_arm/wrist/pitch: {p: 1000.0, d: 60, i: 100, i_clamp: 500.0}
      r2/left_arm/wrist/yaw: {p: 1000.0, d: 60, i: 100, i_clamp: 500.0}
    follow_joint_trajectory:
      joints:
        - r2/left_arm/joint0
        - r2/left_arm/joint1
        - r2/left_arm/joint2
        - r2/left_arm/joint3
        - r2/left_arm/joint4
        - r2/left_arm/wrist/pitch
        - r2/left_arm/wrist/yaw
      constraints:
        goal_time: 10.0
        r2/left_arm/joint0:
          goal: 0.2
        r2/left_arm/joint1:
          goal: 0.2
        r2/left_arm/joint2:
          goal: 0.2
        r2/left_arm/joint3:
          goal: 0.2
        r2/left_arm/joint4:
          goal: 0.2
        r2/left_arm/wrist/pitch:
          goal: 0.2
        r2/left_arm/wrist/yaw:
          goal: 0.2
      state_publish_rate:  25            # Override default
      action_monitor_rate: 30            # Override default
      stop_trajectory_duration: 0        # Override default

  waist_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - r2/waist/joint0
    gains:
      r2/waist/joint0: {p: 1000.0, d: 700, i: 100, i_clamp: 500.0}
    follow_joint_trajectory_node:
      joints:
        - r2/waist/joint0
      constraints:
        goal_time: 5.0
        r2/waist/joint0:
          goal: 0.2
      state_publish_rate:  25            # Override default
      action_monitor_rate: 30            # Override default
      stop_trajectory_duration: 0        # Override default

  neck_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - r2/neck/joint0
      - r2/neck/joint1
      - r2/neck/joint2
    gains:
      r2/neck/joint0: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/neck/joint1: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/neck/joint2: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
    follow_joint_trajectory_node:
      joints:
        - r2/neck/joint0
        - r2/neck/joint1
        - r2/neck/joint2
      constraints:
        goal_time: 5.0
        r2/neck/joint0:
          goal: 0.2
        r2/neck/joint1:
          goal: 0.2
        r2/neck/joint2:
          goal: 0.2
      state_publish_rate:  25            # Override default
      action_monitor_rate: 30            # Override default
      stop_trajectory_duration: 0        # Override default


  l_hand_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - r2/left_arm/hand/index/yaw
      - r2/left_arm/hand/index/proximal
      - r2/left_arm/hand/index/medial
      - r2/left_arm/hand/ringlittle/little
      - r2/left_arm/hand/ringlittle/littleMedial
      - r2/left_arm/hand/middle/yaw
      - r2/left_arm/hand/middle/proximal
      - r2/left_arm/hand/middle/medial
      - r2/left_arm/hand/ringlittle/ring
      - r2/left_arm/hand/ringlittle/ringMedial
      - r2/left_arm/hand/thumb/roll
      - r2/left_arm/hand/thumb/proximal
      - r2/left_arm/hand/thumb/medial
      - r2/left_arm/hand/thumb/distal
    gains:
      r2/left_arm/hand/index/yaw: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/left_arm/hand/index/proximal: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/left_arm/hand/index/medial: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/left_arm/hand/ringlittle/little: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/left_arm/hand/ringlittle/littleMedial: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/left_arm/hand/middle/yaw: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/left_arm/hand/middle/proximal: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/left_arm/hand/middle/medial: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/left_arm/hand/ringlittle/ring: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/left_arm/hand/ringlittle/ringMedial: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/left_arm/hand/thumb/roll: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/left_arm/hand/thumb/proximal: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/left_arm/hand/thumb/medial: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/left_arm/hand/thumb/distal: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
    follow_joint_trajectory_node:
      joints:
        - r2/left_arm/hand/index/yaw
        - r2/left_arm/hand/index/proximal
        - r2/left_arm/hand/index/medial
        - r2/left_arm/hand/ringlittle/little
        - r2/left_arm/hand/ringlittle/littleMedial
        - r2/left_arm/hand/middle/yaw
        - r2/left_arm/hand/middle/proximal
        - r2/left_arm/hand/middle/medial
        - r2/left_arm/hand/ringlittle/ring
        - r2/left_arm/hand/ringlittle/ringMedial
        - r2/left_arm/hand/thumb/roll
        - r2/left_arm/hand/thumb/proximal
        - r2/left_arm/hand/thumb/medial
        - r2/left_arm/hand/thumb/distal
      constraints:
        goal_time: 2.0
        r2/left_arm/hand/index/yaw:
          goal: 0.2
        r2/left_arm/hand/index/proximal:
          goal: 0.2
        r2/left_arm/hand/index/medial:
          goal: 0.2
        r2/left_arm/hand/ringlittle/little:
          goal: 0.2
        r2/left_arm/hand/ringlittle/littleMedial:
          goal: 0.2
        r2/left_arm/hand/middle/yaw:
          goal: 0.2
        r2/left_arm/hand/middle/proximal:
          goal: 0.2
        r2/left_arm/hand/middle/medial:
          goal: 0.2
        r2/left_arm/hand/ringlittle/ring:
          goal: 0.2
        r2/left_arm/hand/ringlittle/ringMedial:
          goal: 0.2
        r2/left_arm/hand/thumb/roll:
          goal: 0.2
        r2/left_arm/hand/thumb/proximal:
          goal: 0.2
        r2/left_arm/hand/thumb/medial:
          goal: 0.2
        r2/left_arm/hand/thumb/distal:
          goal: 0.2
      state_publish_rate:  25            # Override default
      action_monitor_rate: 30            # Override default
      stop_trajectory_duration: 0        # Override default


  r_hand_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - r2/right_arm/hand/index/yaw
      - r2/right_arm/hand/index/proximal
      - r2/right_arm/hand/index/medial
      - r2/right_arm/hand/ringlittle/little
      - r2/right_arm/hand/ringlittle/littleMedial
      - r2/right_arm/hand/middle/yaw
      - r2/right_arm/hand/middle/proximal
      - r2/right_arm/hand/middle/medial
      - r2/right_arm/hand/ringlittle/ring
      - r2/right_arm/hand/ringlittle/ringMedial
      - r2/right_arm/hand/thumb/roll
      - r2/right_arm/hand/thumb/proximal
      - r2/right_arm/hand/thumb/medial
      - r2/right_arm/hand/thumb/distal
    gains:
      r2/right_arm/hand/index/yaw: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/right_arm/hand/index/proximal: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/right_arm/hand/index/medial: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/right_arm/hand/ringlittle/little: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/right_arm/hand/ringlittle/littleMedial: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/right_arm/hand/middle/yaw: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/right_arm/hand/middle/proximal: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/right_arm/hand/middle/medial: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/right_arm/hand/ringlittle/ring: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/right_arm/hand/ringlittle/ringMedial: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/right_arm/hand/thumb/roll: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/right_arm/hand/thumb/proximal: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/right_arm/hand/thumb/medial: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
      r2/right_arm/hand/thumb/distal: {p: 1.0, d: 0, i: 0, i_clamp: 4.0}
    follow_joint_trajectory_node:
      joints:
        - r2/right_arm/hand/index/yaw
        - r2/right_arm/hand/index/proximal
        - r2/right_arm/hand/index/medial
        - r2/right_arm/hand/ringlittle/little
        - r2/right_arm/hand/ringlittle/littleMedial
        - r2/right_arm/hand/middle/yaw
        - r2/right_arm/hand/middle/proximal
        - r2/right_arm/hand/middle/medial
        - r2/right_arm/hand/ringlittle/ring
        - r2/right_arm/hand/ringlittle/ringMedial
        - r2/right_arm/hand/thumb/roll
        - r2/right_arm/hand/thumb/proximal
        - r2/right_arm/hand/thumb/medial
        - r2/right_arm/hand/thumb/distal
      constraints:
        goal_time: 2.0
        r2/right_arm/hand/index/yaw:
          goal: 0.2
        r2/right_arm/hand/index/proximal:
          goal: 0.2
        r2/right_arm/hand/index/medial:
          goal: 0.2
        r2/right_arm/hand/ringlittle/little:
          goal: 0.2
        r2/right_arm/hand/ringlittle/littleMedial:
          goal: 0.2
        r2/right_arm/hand/middle/yaw:
          goal: 0.2
        r2/right_arm/hand/middle/proximal:
          goal: 0.2
        r2/right_arm/hand/middle/medial:
          goal: 0.2
        r2/right_arm/hand/ringlittle/ring:
          goal: 0.2
        r2/right_arm/hand/ringlittle/ringMedial:
          goal: 0.2
        r2/right_arm/hand/thumb/roll:
          goal: 0.2
        r2/right_arm/hand/thumb/proximal:
          goal: 0.2
        r2/right_arm/hand/thumb/medial:
          goal: 0.2
        r2/right_arm/hand/thumb/distal:
          goal: 0.2

      state_publish_rate:  25            # Override default
      action_monitor_rate: 30            # Override default
      stop_trajectory_duration: 0        # Override default


