r2_sim_params:
    # list of initial joint positions
    # omitted joints default to 0.0
    initial_position: # start the robot in this position
        radians: false
        position:
          r2:
              left_leg: 
                  joint0: 0.0 # 50.0
                  joint1: 0.0
                  joint2: 0.0 # -10.0
                  joint3: 0.0 # 100.0
                  joint4: 0.0
                  joint5: 0.0 # 53.0
                  joint6: 0.0 # -100.0
                  gripper:
                      joint0: 0
              right_leg: 
                  joint0: 0.0 # -50.0
                  joint1: 0.0
                  joint2: 0.0 # 10.0
                  joint3: 0.0 # 100.0
                  joint4: 0.0
                  joint5: 0.0 # 53.0
                  joint6: 0.0 # -100.0
                  gripper:
                      joint0: 0
                        
    # PID values are [kp, ki, kd, imax, imin, command_max, command_min]
    # Only the first 3 are required, the others default to 0.0 meaning they are unused
    # position_pid and velocity_pid are available and should be set for position or velocity control, respectively
    position_pid: 
        r2:
            left_leg:
                joint0:
                    [800, 0, 25]
                joint1:
                    [800, 0, 40]
                joint2:
                    [450, 0, 10]
                joint3:
                    [1000, 0, 20]
                joint4:
                    [350, 0, 2]
                joint5:
                    [600, 0, 20]
                joint6:
                    [200, 0, 2]
                gripper:
                    joint0:
                        [100, 0, 1]
                    jawLeft:
                        [100, 0, 1]
                    jawRight:
                        [100, 0, 1]
                        
            right_leg:
                joint0:
                    [800, 0, 25]
                joint1:
                    [800, 0, 40]
                joint2:
                    [450, 0, 10]
                joint3:
                    [1000, 0, 20]
                joint4:
                    [350, 0, 2]
                joint5:
                    [600, 0, 20]
                joint6:
                    [200, 0, 2]
                gripper:
                    joint0:
                        [100, 0, 1]
                    jawLeft:
                        [100, 0, 1]
                    jawRight:
                        [100, 0, 1]
                    
    # list of dependencies with a scale to apply to commands (pos, vel, effort)
    # parent:
    #     children: list of dependent joints
    #     factors: list of scale values
    # a joint can be dependent on itself if a scale needs to be applied to commands
    dependency:
        r2:
            left_leg/gripper/joint0:
                children: 
                    - r2/left_leg/gripper/joint0
                    - r2/left_leg/gripper/jawLeft
                    - r2/left_leg/gripper/jawRight
                factors: 
                    - 1.0
                    - 1.0
                    - 1.0
                
            right_leg/gripper/joint0:
                children: 
                    - r2/right_leg/gripper/joint0
                    - r2/right_leg/gripper/jawLeft
                    - r2/right_leg/gripper/jawRight
                factors: 
                    - 1.0
                    - 1.0
                    - 1.0

